package com.teste.consultar.recyclerview.src.model;

import java.util.ArrayList;

/**
 * Created by: Danilo A. Santos on 02/20/18.
 */
public class Filme {

    private String titulo;
    private String ano;
    private String genero;

    public Filme(){}

    public Filme(String titulo, String ano, String genero) {
        this.titulo = titulo;
        this.ano = ano;
        this.genero = genero;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getAno() {
        return ano;
    }

    public void setAno(String ano) {
        this.ano = ano;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public static ArrayList<Filme> getListaFilmes() {
        ArrayList<Filme> listaFilmes = new ArrayList<>();

        listaFilmes.add(new Filme("Captain America: The Winter Soldier","2014","Adventure"));
        listaFilmes.add(new Filme("Dawn of the Planet of the Apes","2014","Drama"));
        listaFilmes.add(new Filme("Guardians of the Galaxy","2014","Adventure"));
        listaFilmes.add(new Filme("Interstellar","2014","Adventure"));
        listaFilmes.add(new Filme("Maleficent","2014","Adventure"));
        listaFilmes.add(new Filme("The Amazing Spider-Man 2","2014","Adventure"));
        listaFilmes.add(new Filme("The Hobbit: The Battle of the Five Armies","2014","Adventure"));
        listaFilmes.add(new Filme("The Hunger Games: Mockingjay - Part 1","2014","Adventure"));
        listaFilmes.add(new Filme("Transformers: Age of Extinction","2014","Adventure"));
        listaFilmes.add(new Filme("X-Men: Days of Future Past","2014","Adventure"));
        listaFilmes.add(new Filme("Despicable Me 2","2013","Comedy"));
        listaFilmes.add(new Filme("Fast & Furious 6","2013","Crime"));
        listaFilmes.add(new Filme("Frozen","2013","Animation"));
        listaFilmes.add(new Filme("Gravity","2013","Sci-Fi"));
        listaFilmes.add(new Filme("Iron Man 3","2013","Adventure"));
        listaFilmes.add(new Filme("Man of Steel","2013","Adventure"));
        listaFilmes.add(new Filme("Monsters University","2013","Animation"));
        listaFilmes.add(new Filme("The Hobbit: The Desolation of Smaug","2013","Adventure"));
        listaFilmes.add(new Filme("The Hunger Games: Catching Fire","2013","Sci-Fi"));
        listaFilmes.add(new Filme("Thor: The Dark World","2013","Adventure"));
        listaFilmes.add(new Filme("Ice Age: Continental Drift","2012","Animation"));
        listaFilmes.add(new Filme("Madagascar 3: Europe's Most Wanted","2012","Adventure"));
        listaFilmes.add(new Filme("Men in Black 3","2012","Comedy"));
        listaFilmes.add(new Filme("Skyfall","2012","Adventure"));
        listaFilmes.add(new Filme("The Amazing Spider-Man","2012","Adventure"));
        listaFilmes.add(new Filme("The Avengers","2012","Adventure"));
        listaFilmes.add(new Filme("The Dark Knight Rises","2012","Action"));
        listaFilmes.add(new Filme("The Hobbit: An Unexpected Journey","2012","Adventure"));
        listaFilmes.add(new Filme("The Hunger Games","2012","Adventure"));
        listaFilmes.add(new Filme("The Twilight Saga: Breaking Dawn - Part 2","2012","Drama"));
        listaFilmes.add(new Filme("Cars 2","2011","Animation"));
        listaFilmes.add(new Filme("Fast Five","2011","Crime"));
        listaFilmes.add(new Filme("Harry Potter and the Deathly Hallows - Part 2","2011","Fantasy"));
        listaFilmes.add(new Filme("Kung Fu Panda 2","2011","Adventure"));
        listaFilmes.add(new Filme("Mission: Impossible - Ghost Protocol","2011","Adventure"));
        listaFilmes.add(new Filme("Pirates of the Caribbean: On Stranger Tides","2011","Adventure"));
        listaFilmes.add(new Filme("The Hangover Part II","2011","Desconhecido"));
        listaFilmes.add(new Filme("The Smurfs","2011","Animation"));
        listaFilmes.add(new Filme("The Twilight Saga: Breaking Dawn - Part 1","2011","Drama"));
        listaFilmes.add(new Filme("Transformers: Dark of the Moon","2011","Adventure"));
        listaFilmes.add(new Filme("Alice in Wonderland","2010","Family"));
        listaFilmes.add(new Filme("Despicable Me","2010","Comedy"));
        listaFilmes.add(new Filme("Harry Potter and the Deathly Hallows - Part 1","2010","Family"));
        listaFilmes.add(new Filme("How to Train Your Dragon","2010","Animation"));
        listaFilmes.add(new Filme("Inception","2010","Mystery"));
        listaFilmes.add(new Filme("Iron Man 2","2010","Adventure"));
        listaFilmes.add(new Filme("Shrek Forever After","2010","Animation"));
        listaFilmes.add(new Filme("Tangled","2010","Comedy"));
        listaFilmes.add(new Filme("The Twilight Saga: Eclipse","2010","Drama"));
        listaFilmes.add(new Filme("Toy Story 3","2010","Animation"));
        listaFilmes.add(new Filme("2012","2009","Adventure"));
        listaFilmes.add(new Filme("Angels & Demons","2009","Mystery"));
        listaFilmes.add(new Filme("Avatar","2009","Adventure"));
        listaFilmes.add(new Filme("Harry Potter and the Half-Blood Prince","2009","Family"));
        listaFilmes.add(new Filme("Ice Age: Dawn of the Dinosaurs","2009","Adventure"));
        listaFilmes.add(new Filme("Sherlock Holmes","2009","Adventure"));
        listaFilmes.add(new Filme("The Hangover","2009",""));
        listaFilmes.add(new Filme("The Twilight Saga: New Moon","2009","Drama"));
        listaFilmes.add(new Filme("Transformers: Revenge of the Fallen","2009","Adventure"));
        listaFilmes.add(new Filme("Up","2009","Animation"));
        listaFilmes.add(new Filme("Hancock","2008","Action"));
        listaFilmes.add(new Filme("Indiana Jones and the Kingdom of the Crystal Skull","2008","Action"));
        listaFilmes.add(new Filme("Iron Man","2008","Adventure"));
        listaFilmes.add(new Filme("Kung Fu Panda","2008","Adventure"));
        listaFilmes.add(new Filme("Madagascar: Escape 2 Africa","2008","Adventure"));
        listaFilmes.add(new Filme("Mamma Mia!","2008","Musical"));
        listaFilmes.add(new Filme("Quantum of Solace","2008","Action"));
        listaFilmes.add(new Filme("The Chronicles of Narnia: Prince Caspian","2008","Adventure"));
        listaFilmes.add(new Filme("The Dark Knight","2008","Crime"));
        listaFilmes.add(new Filme("WALL-E","2008","Animation"));
        listaFilmes.add(new Filme("300","2007","Fantasy"));
        listaFilmes.add(new Filme("Harry Potter and the Order of the Phoenix","2007","Family"));
        listaFilmes.add(new Filme("I Am Legend","2007","Sci-Fi"));
        listaFilmes.add(new Filme("National Treasure: Book of Secrets","2007","Adventure"));
        listaFilmes.add(new Filme("Pirates of the Caribbean: At World's End","2007","Adventure"));
        listaFilmes.add(new Filme("Ratatouille","2007","Comedy"));
        listaFilmes.add(new Filme("Shrek the Third","2007","Animation"));
        listaFilmes.add(new Filme("Spider-Man 3","2007","Action"));
        listaFilmes.add(new Filme("The Simpsons Movie","2007","Animation"));
        listaFilmes.add(new Filme("Transformers","2007","Adventure"));
        listaFilmes.add(new Filme("Cars","2006","Animation"));
        listaFilmes.add(new Filme("Casino Royale","2006","Adventure"));
        listaFilmes.add(new Filme("Happy Feet","2006","Comedy"));
        listaFilmes.add(new Filme("Ice Age: The Meltdown","2006","Adventure"));
        listaFilmes.add(new Filme("Mission: Impossible III","2006","Adventure"));
        listaFilmes.add(new Filme("Night at the Museum","2006","Adventure"));
        listaFilmes.add(new Filme("Pirates of the Caribbean: Dead Man's Chest","2006","Adventure"));
        listaFilmes.add(new Filme("Superman Returns","2006","Adventure"));
        listaFilmes.add(new Filme("The Da Vinci Code","2006","Mystery"));
        listaFilmes.add(new Filme("X-Men: The Last Stand","2006","Adventure"));
        listaFilmes.add(new Filme("Batman Begins","2005","Action"));
        listaFilmes.add(new Filme("Charlie and the Chocolate Factory","2005","Adventure"));
        listaFilmes.add(new Filme("Harry Potter and the Goblet of Fire","2005","Family"));
        listaFilmes.add(new Filme("Hitch","2005","Comedy"));
        listaFilmes.add(new Filme("King Kong","2005","Adventure"));
        listaFilmes.add(new Filme("Madagascar","2005","Animation"));
        listaFilmes.add(new Filme("Mr. & Mrs. Smith","2005","Comedy"));
        listaFilmes.add(new Filme("Star Wars Episode III: Revenge of the Sith","2005","Adventure"));
        listaFilmes.add(new Filme("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe","2005","Family"));
        listaFilmes.add(new Filme("War of the Worlds","2005","Sci-Fi"));
        listaFilmes.add(new Filme("Harry Potter and the Prisoner of Azkaban","2004","Family"));
        listaFilmes.add(new Filme("Meet the Fockers","2004","Comedy"));
        listaFilmes.add(new Filme("Ocean's Twelve","2004","Crime"));
        listaFilmes.add(new Filme("Shark Tale","2004","Adventure"));
        listaFilmes.add(new Filme("Shrek 2","2004","Animation"));
        listaFilmes.add(new Filme("Spider-Man 2","2004","Action"));
        listaFilmes.add(new Filme("The Day After Tomorrow","2004","Adventure"));
        listaFilmes.add(new Filme("The Incredibles","2004","Adventure"));
        listaFilmes.add(new Filme("The Passion of the Christ","2004","Desconhecido"));
        listaFilmes.add(new Filme("Troy","2004","Desconhecido"));
        listaFilmes.add(new Filme("Bad Boys II","2003","Comedy"));
        listaFilmes.add(new Filme("Bruce Almighty","2003","Drama"));
        listaFilmes.add(new Filme("Finding Nemo","2003","Animation"));
        listaFilmes.add(new Filme("Pirates of the Caribbean: The Curse of the Black Pearl","2003","Adventure"));
        listaFilmes.add(new Filme("Terminator 3: Rise of the Machines","2003","Action"));
        listaFilmes.add(new Filme("The Last Samurai","2003","Drama"));
        listaFilmes.add(new Filme("The Lord of the Rings: The Return of the King","2003","Adventure"));
        listaFilmes.add(new Filme("The Matrix Reloaded","2003","Action"));
        listaFilmes.add(new Filme("The Matrix Revolutions","2003","Action"));
        listaFilmes.add(new Filme("X2","2003","Adventure"));
        listaFilmes.add(new Filme("Die Another Day","2002","Adventure"));
        listaFilmes.add(new Filme("Harry Potter and the Chamber of Secrets","2002","Family"));
        listaFilmes.add(new Filme("Ice Age","2002","Animation"));
        listaFilmes.add(new Filme("Men in Black II","2002","Comedy"));
        listaFilmes.add(new Filme("Minority Report","2002","Mystery"));
        listaFilmes.add(new Filme("My Big Fat Greek Wedding","2002","Comedy"));
        listaFilmes.add(new Filme("Signs","2002","Sci-Fi"));
        listaFilmes.add(new Filme("Spider-Man","2002","Action"));
        listaFilmes.add(new Filme("Star Wars Episode II: Attack of the Clones","2002","Adventure"));
        listaFilmes.add(new Filme("The Lord of the Rings: The Two Towers","2002","Adventure"));
        listaFilmes.add(new Filme("Hannibal","2001","Drama"));
        listaFilmes.add(new Filme("Harry Potter and the Sorcerer's Stone","2001","Family"));
        listaFilmes.add(new Filme("Jurassic Park III","2001","Adventure"));
        listaFilmes.add(new Filme("Monsters, Inc.","2001","Animation"));
        listaFilmes.add(new Filme("Ocean's Eleven","2001","Crime"));
        listaFilmes.add(new Filme("Pearl Harbor","2001","Drama"));
        listaFilmes.add(new Filme("Planet of the Apes","2001","Adventure"));
        listaFilmes.add(new Filme("Shrek","2001","Animation"));
        listaFilmes.add(new Filme("The Lord of the Rings: The Fellowship of the Ring","2001","Adventure"));
        listaFilmes.add(new Filme("The Mummy Returns","2001","Adventure"));
        listaFilmes.add(new Filme("Cast Away","2000","Adventure"));
        listaFilmes.add(new Filme("Dinosaur","2000","Animation"));
        listaFilmes.add(new Filme("Gladiator","2000","Action"));
        listaFilmes.add(new Filme("How the Grinch Stole Christmas","2000","Family"));
        listaFilmes.add(new Filme("Meet the Parents","2000","Desconhecido"));
        listaFilmes.add(new Filme("Mission: Impossible II","2000","Adventure"));
        listaFilmes.add(new Filme("The Perfect Storm","2000","Adventure"));
        listaFilmes.add(new Filme("What Lies Beneath","2000","Horror"));
        listaFilmes.add(new Filme("What Women Want","2000","Fantasy"));
        listaFilmes.add(new Filme("X-Men","2000","Adventure"));
        listaFilmes.add(new Filme("American Beauty","1999","Drama"));
        listaFilmes.add(new Filme("Austin Powers: The Spy Who Shagged Me","1999","Adventure"));
        listaFilmes.add(new Filme("Notting Hill","1999","Drama"));
        listaFilmes.add(new Filme("Star Wars Episode I: The Phantom Menace","1999","Adventure"));
        listaFilmes.add(new Filme("Tarzan","1999","Animation"));
        listaFilmes.add(new Filme("The Matrix","1999","Action"));
        listaFilmes.add(new Filme("The Mummy","1999","Adventure"));
        listaFilmes.add(new Filme("The Sixth Sense","1999","Mystery"));
        listaFilmes.add(new Filme("The World Is Not Enough","1999","Adventure"));
        listaFilmes.add(new Filme("Toy Story 2","1999","Animation"));
        listaFilmes.add(new Filme("A Bug's Life","1998","Animation"));
        listaFilmes.add(new Filme("Armageddon","1998","Adventure"));
        listaFilmes.add(new Filme("Deep Impact","1998","Drama"));
        listaFilmes.add(new Filme("Dr. Dolittle","1998","Family"));
        listaFilmes.add(new Filme("Godzilla","1998","Sci-Fi"));
        listaFilmes.add(new Filme("Lethal Weapon 4","1998","Crime"));
        listaFilmes.add(new Filme("Mulan","1998","Animation"));
        listaFilmes.add(new Filme("Saving Private Ryan","1998","Drama"));
        listaFilmes.add(new Filme("Shakespeare in Love","1998","Drama"));
        listaFilmes.add(new Filme("There's Something About Mary","1998","Comedy"));
        listaFilmes.add(new Filme("Air Force One","1997","Adventure"));
        listaFilmes.add(new Filme("As Good as It Gets","1997","Drama"));
        listaFilmes.add(new Filme("Liar Liar","1997","Desconhecido"));
        listaFilmes.add(new Filme("Men in Black","1997","Comedy"));
        listaFilmes.add(new Filme("My Best Friend's Wedding","1997","Comedy"));
        listaFilmes.add(new Filme("The Fifth Element","1997","Adventure"));
        listaFilmes.add(new Filme("The Full Monty","1997","Drama"));
        listaFilmes.add(new Filme("The Lost World: Jurassic Park","1997","Adventure"));
        listaFilmes.add(new Filme("Titanic","1997","Drama"));
        listaFilmes.add(new Filme("Tomorrow Never Dies","1997","Adventure"));
        listaFilmes.add(new Filme("101 Dalmatians","1996","Comedy"));
        listaFilmes.add(new Filme("Eraser","1996","Drama"));
        listaFilmes.add(new Filme("Independence Day","1996","Adventure"));
        listaFilmes.add(new Filme("Jerry Maguire","1996","Drama"));
        listaFilmes.add(new Filme("Mission: Impossible","1996","Adventure"));
        listaFilmes.add(new Filme("Ransom","1996","Crime"));
        listaFilmes.add(new Filme("The Hunchback of Notre Dame","1996","Drama"));
        listaFilmes.add(new Filme("The Nutty Professor","1996","Romance"));
        listaFilmes.add(new Filme("The Rock","1996","Adventure"));
        listaFilmes.add(new Filme("Twister","1996","Adventure"));
        listaFilmes.add(new Filme("Apollo 13","1995","Drama"));
        listaFilmes.add(new Filme("Batman Forever","1995","Adventure"));
        listaFilmes.add(new Filme("Casper","1995","Family"));
        listaFilmes.add(new Filme("Die Hard with a Vengeance","1995","Adventure"));
        listaFilmes.add(new Filme("GoldenEye","1995","Adventure"));
        listaFilmes.add(new Filme("Jumanji","1995","Family"));
        listaFilmes.add(new Filme("Pocahontas","1995","Animation"));
        listaFilmes.add(new Filme("Seven","1995","Drama"));
        listaFilmes.add(new Filme("Toy Story","1995","Animation"));
        listaFilmes.add(new Filme("Waterworld","1995","Adventure"));
        listaFilmes.add(new Filme("Clear and Present Danger","1994","Crime"));
        listaFilmes.add(new Filme("Dumb and Dumber","1994","Desconhecido"));
        listaFilmes.add(new Filme("Forrest Gump","1994","Drama"));
        listaFilmes.add(new Filme("Four Weddings and a Funeral","1994","Drama"));
        listaFilmes.add(new Filme("Interview with the Vampire: The Vampire Chronicles","1994","Horror"));
        listaFilmes.add(new Filme("Speed","1994","Crime"));
        listaFilmes.add(new Filme("The Flintstones","1994","Family"));
        listaFilmes.add(new Filme("The Lion King","1994","Animation"));
        listaFilmes.add(new Filme("The Mask","1994","Crime"));
        listaFilmes.add(new Filme("True Lies","1994","Comedy"));
        listaFilmes.add(new Filme("Cliffhanger","1993","Adventure"));
        listaFilmes.add(new Filme("Indecent Proposal","1993","Drama"));
        listaFilmes.add(new Filme("Jurassic Park","1993","Sci-Fi"));
        listaFilmes.add(new Filme("Mrs. Doubtfire","1993","Drama"));
        listaFilmes.add(new Filme("Philadelphia","1993","Desconhecido"));
        listaFilmes.add(new Filme("Schindler's List","1993","Drama"));
        listaFilmes.add(new Filme("Sleepless in Seattle","1993","Drama"));
        listaFilmes.add(new Filme("The Firm","1993","Mystery"));
        listaFilmes.add(new Filme("The Fugitive","1993","Adventure"));
        listaFilmes.add(new Filme("The Pelican Brief","1993","Crime"));
        listaFilmes.add(new Filme("A Few Good Men","1992","Drama"));
        listaFilmes.add(new Filme("Aladdin","1992","Animation"));
        listaFilmes.add(new Filme("Basic Instinct","1992","Mystery"));
        listaFilmes.add(new Filme("Batman Returns","1992","Desconhecido"));
        listaFilmes.add(new Filme("Bram Stoker's Dracula","1992","Horror"));
        listaFilmes.add(new Filme("Home Alone 2: Lost in New York","1992","Comedy"));
        listaFilmes.add(new Filme("Lethal Weapon 3","1992","Crime"));
        listaFilmes.add(new Filme("Sister Act","1992","Comedy"));
        listaFilmes.add(new Filme("The Bodyguard","1992","Drama"));
        listaFilmes.add(new Filme("Wayne's World","1992","Comedy"));
        listaFilmes.add(new Filme("Beauty and the Beast","1991","Family"));
        listaFilmes.add(new Filme("Cape Fear","1991","Crime"));
        listaFilmes.add(new Filme("City Slickers","1991","Comedy"));
        listaFilmes.add(new Filme("Hook","1991","Comedy"));
        listaFilmes.add(new Filme("Hot Shots!","1991","Desconhecido"));
        listaFilmes.add(new Filme("JFK","1991","History"));
        listaFilmes.add(new Filme("Robin Hood: Prince of Thieves","1991","Adventure"));
        listaFilmes.add(new Filme("Terminator 2: Judgment Day","1991","Action"));
        listaFilmes.add(new Filme("The Addams Family","1991","Comedy"));
        listaFilmes.add(new Filme("The Silence of the Lambs","1991","Desconhecido"));
        listaFilmes.add(new Filme("Back to the Future Part III","1990","Comedy"));
        listaFilmes.add(new Filme("Dances with Wolves","1990","Drama"));
        listaFilmes.add(new Filme("Die Hard 2","1990","Action"));
        listaFilmes.add(new Filme("Ghost","1990","Fantasy"));
        listaFilmes.add(new Filme("Home Alone","1990","Comedy"));
        listaFilmes.add(new Filme("Kindergarten Cop","1990","Comedy"));
        listaFilmes.add(new Filme("Presumed Innocent","1990","Drama"));
        listaFilmes.add(new Filme("Pretty Woman","1990","Comedy"));
        listaFilmes.add(new Filme("Teenage Mutant Ninja Turtles","1990","Adventure"));
        listaFilmes.add(new Filme("Total Recall","1990","Sci-Fi"));
        listaFilmes.add(new Filme("Back to the Future Part II","1989","Comedy"));
        listaFilmes.add(new Filme("Batman","1989","Action"));
        listaFilmes.add(new Filme("Born on the Fourth of July","1989","Drama"));
        listaFilmes.add(new Filme("Dead Poets Society","1989","Desconhecido"));
        listaFilmes.add(new Filme("Ghostbusters II","1989","Fantasy"));
        listaFilmes.add(new Filme("Honey, I Shrunk the Kids","1989","Comedy"));
        listaFilmes.add(new Filme("Indiana Jones and the Last Crusade","1989","Action"));
        listaFilmes.add(new Filme("Lethal Weapon 2","1989","Crime"));
        listaFilmes.add(new Filme("Look Who's Talking","1989","Comedy"));
        listaFilmes.add(new Filme("The Little Mermaid","1989","Family"));
        listaFilmes.add(new Filme("Crocodile Dundee II","1988","Adventure"));
        listaFilmes.add(new Filme("Beetlejuice","1988","Desconhecido"));
        listaFilmes.add(new Filme("Big","1988","Drama"));
        listaFilmes.add(new Filme("Cocktail","1988","Drama"));
        listaFilmes.add(new Filme("Coming to America","1988","Comedy"));
        listaFilmes.add(new Filme("Die Hard","1988","Action"));
        listaFilmes.add(new Filme("Rain Man","1988","Desconhecido"));
        listaFilmes.add(new Filme("The Naked Gun: From the Files of Police Squad!","1988","Comedy"));
        listaFilmes.add(new Filme("Twins","1988","Desconhecido"));
        listaFilmes.add(new Filme("Who Framed Roger Rabbit","1988","Comedy"));
        listaFilmes.add(new Filme("Beverly Hills Cop II","1987","Comedy"));
        listaFilmes.add(new Filme("Fatal Attraction","1987","Drama"));
        listaFilmes.add(new Filme("Good Morning, Vietnam","1987","Drama"));
        listaFilmes.add(new Filme("Lethal Weapon","1987","Crime"));
        listaFilmes.add(new Filme("Moonstruck","1987","Drama"));
        listaFilmes.add(new Filme("Stakeout","1987","Comedy"));
        listaFilmes.add(new Filme("The Secret of My Success","1987","Desconhecido"));
        listaFilmes.add(new Filme("The Untouchables","1987","Drama"));
        listaFilmes.add(new Filme("The Witches of Eastwick","1987","Fantasy"));
        listaFilmes.add(new Filme("Three Men and a Baby","1987","Drama"));
        listaFilmes.add(new Filme("Crocodile Dundee","1986","Comedy"));
        listaFilmes.add(new Filme("Aliens","1986","Adventure"));
        listaFilmes.add(new Filme("An American Tail","1986","Comedy"));
        listaFilmes.add(new Filme("Back to School","1986","Romance"));
        listaFilmes.add(new Filme("Platoon","1986","Drama"));
        listaFilmes.add(new Filme("Ruthless People","1986","Comedy"));
        listaFilmes.add(new Filme("Star Trek IV: The Voyage Home","1986","Adventure"));
        listaFilmes.add(new Filme("The Golden Child","1986","Adventure"));
        listaFilmes.add(new Filme("The Karate Kid, Part II","1986","Family"));
        listaFilmes.add(new Filme("Top Gun","1986","Drama"));
        listaFilmes.add(new Filme("Back to the Future","1985","Comedy"));
        listaFilmes.add(new Filme("Cocoon","1985","Desconhecido"));
        listaFilmes.add(new Filme("Out Of Africa","1985","Drama"));
        listaFilmes.add(new Filme("Rambo: First Blood Part II","1985","Adventure"));
        listaFilmes.add(new Filme("Rocky IV","1985","Drama"));
        listaFilmes.add(new Filme("Spies Like Us","1985","Adventure"));
        listaFilmes.add(new Filme("The Color Purple","1985","Desconhecido"));
        listaFilmes.add(new Filme("The Goonies","1985","Comedy"));
        listaFilmes.add(new Filme("The Jewel of the Nile","1985","Adventure"));
        listaFilmes.add(new Filme("Witness","1985","Drama"));
        listaFilmes.add(new Filme("Beverly Hills Cop","1984","Action"));
        listaFilmes.add(new Filme("Footloose","1984","Music"));
        listaFilmes.add(new Filme("Ghostbusters","1984","Comedy"));
        listaFilmes.add(new Filme("Gremlins","1984","Comedy"));
        listaFilmes.add(new Filme("Indiana Jones and the Temple of Doom","1984","Adventure"));
        listaFilmes.add(new Filme("Police Academy","1984","Desconhecido"));
        listaFilmes.add(new Filme("Romancing the Stone","1984","Adventure"));
        listaFilmes.add(new Filme("Star Trek III: The Search for Spock","1984","Adventure"));
        listaFilmes.add(new Filme("The Karate Kid","1984","Drama"));
        listaFilmes.add(new Filme("The Terminator","1984","Action"));
        listaFilmes.add(new Filme("Flashdance","1983","Music"));
        listaFilmes.add(new Filme("Mr. Mom","1983","Comedy"));
        listaFilmes.add(new Filme("Octopussy","1983","Adventure"));
        listaFilmes.add(new Filme("Risky Business","1983","Crime"));
        listaFilmes.add(new Filme("Star Wars Episode VI: Return of the Jedi","1983","Adventure"));
        listaFilmes.add(new Filme("Staying Alive","1983","Music"));
        listaFilmes.add(new Filme("Sudden Impact","1983","Action"));
        listaFilmes.add(new Filme("Terms of Endearment","1983","Comedy"));
        listaFilmes.add(new Filme("Trading Places","1983","Desconhecido"));
        listaFilmes.add(new Filme("WarGames","1983","Sci-Fi"));
        listaFilmes.add(new Filme("48 Hrs.","1982","Comedy"));
        listaFilmes.add(new Filme("An Officer and a Gentleman","1982","Drama"));
        listaFilmes.add(new Filme("Annie","1982","Drama"));
        listaFilmes.add(new Filme("E.T. the Extra-Terrestrial","1982","Family"));
        listaFilmes.add(new Filme("Poltergeist","1982","Desconhecido"));
        listaFilmes.add(new Filme("Porky's","1982","Desconhecido"));
        listaFilmes.add(new Filme("Rocky III","1982","Drama"));
        listaFilmes.add(new Filme("Star Trek II: The Wrath of Khan","1982","Adventure"));
        listaFilmes.add(new Filme("The Best Little Whorehouse in Texas","1982","Comedy"));
        listaFilmes.add(new Filme("Tootsie","1982","Comedy"));
        listaFilmes.add(new Filme("Arthur","1981","Comedy"));
        listaFilmes.add(new Filme("Chariots of Fire","1981","History"));
        listaFilmes.add(new Filme("For Your Eyes Only","1981","Adventure"));
        listaFilmes.add(new Filme("On Golden Pond","1981","Desconhecido"));
        listaFilmes.add(new Filme("Raiders of the Lost Ark","1981","Action"));
        listaFilmes.add(new Filme("Stripes","1981","Comedy"));
        listaFilmes.add(new Filme("Superman II","1981","Romance"));
        listaFilmes.add(new Filme("The Cannonball Run","1981","Action"));
        listaFilmes.add(new Filme("The Four Seasons","1981","Comedy"));
        listaFilmes.add(new Filme("Time Bandits","1981","Comedy"));
        listaFilmes.add(new Filme("9 to 5","1980","Desconhecido"));
        listaFilmes.add(new Filme("Airplane!","1980","Desconhecido"));
        listaFilmes.add(new Filme("Any Which Way You Can","1980","Action"));
        listaFilmes.add(new Filme("Coal Miner's Daughter","1980","Drama"));
        listaFilmes.add(new Filme("Private Benjamin","1980","Comedy"));
        listaFilmes.add(new Filme("Smokey and the Bandit II","1980","Comedy"));
        listaFilmes.add(new Filme("Star Wars Episode V: The Empire Strikes Back","1980","Action"));
        listaFilmes.add(new Filme("Stir Crazy","1980","Comedy"));
        listaFilmes.add(new Filme("The Blue Lagoon","1980","Drama"));
        listaFilmes.add(new Filme("The Blues Brothers","1980","Comedy"));
        listaFilmes.add(new Filme("10","1979","Comedy"));
        listaFilmes.add(new Filme("Alien","1979","Horror"));
        listaFilmes.add(new Filme("Apocalypse Now","1979","Drama"));
        listaFilmes.add(new Filme("Kramer vs. Kramer","1979","Desconhecido"));
        listaFilmes.add(new Filme("Moonraker","1979","Adventure"));
        listaFilmes.add(new Filme("Rocky II","1979","Drama"));
        listaFilmes.add(new Filme("Star Trek: The Motion Picture","1979","Mystery"));
        listaFilmes.add(new Filme("The Amityville Horror","1979","Drama"));
        listaFilmes.add(new Filme("The Jerk","1979","Desconhecido"));
        listaFilmes.add(new Filme("The Muppet Movie","1979","Comedy"));
        listaFilmes.add(new Filme("Dawn of the Dead","1978","Drama"));
        listaFilmes.add(new Filme("Every Which Way but Loose","1978","Action"));
        listaFilmes.add(new Filme("Grease","1978","Musical"));
        listaFilmes.add(new Filme("Heaven Can Wait","1978","Romance"));
        listaFilmes.add(new Filme("Hooper","1978","Action"));
        listaFilmes.add(new Filme("Jaws 2","1978","Horror"));
        listaFilmes.add(new Filme("National Lampoon's Animal House","1978","Desconhecido"));
        listaFilmes.add(new Filme("Revenge of the Pink Panther","1978","Comedy"));
        listaFilmes.add(new Filme("Superman","1978","Drama"));
        listaFilmes.add(new Filme("The Deer Hunter","1978","Drama"));
        listaFilmes.add(new Filme("A Bridge Too Far","1977","History"));
        listaFilmes.add(new Filme("Annie Hall","1977","Drama"));
        listaFilmes.add(new Filme("Close Encounters of the Third Kind","1977","Drama"));
        listaFilmes.add(new Filme("Oh, God!","1977","Comedy"));
        listaFilmes.add(new Filme("Saturday Night Fever","1977","Music"));
        listaFilmes.add(new Filme("Smokey and the Bandit","1977","Comedy"));
        listaFilmes.add(new Filme("Star Wars","1977","Adventure"));
        listaFilmes.add(new Filme("The Deep","1977","Mystery"));
        listaFilmes.add(new Filme("The Goodbye Girl","1977","Drama"));
        listaFilmes.add(new Filme("The Spy Who Loved Me","1977","Adventure"));
        listaFilmes.add(new Filme("A Star Is Born","1976","Music"));
        listaFilmes.add(new Filme("All the President's Men","1976","Drama"));
        listaFilmes.add(new Filme("In Search of Noah's Ark","1976","Documentary"));
        listaFilmes.add(new Filme("King Kong","1976","Fantasy"));
        listaFilmes.add(new Filme("Midway","1976","Drama"));
        listaFilmes.add(new Filme("Rocky","1976","Drama"));
        listaFilmes.add(new Filme("Silver Streak","1976","Comedy"));
        listaFilmes.add(new Filme("The Enforcer","1976","Crime"));
        listaFilmes.add(new Filme("The Omen","1976","Horror"));
        listaFilmes.add(new Filme("To Fly!","1976","Documentary"));
        listaFilmes.add(new Filme("Aloha, Bobby and Rose","1975","Desconhecido"));
        listaFilmes.add(new Filme("Dog Day Afternoon","1975","Crime"));
        listaFilmes.add(new Filme("Funny Lady","1975","Drama"));
        listaFilmes.add(new Filme("Shampoo","1975","Drama"));
        listaFilmes.add(new Filme("The Apple Dumpling Gang","1975","Family"));
        listaFilmes.add(new Filme("The Other Side of the Mountain","1975","Western"));
        listaFilmes.add(new Filme("The Return of the Pink Panther","1975","Crime"));
        listaFilmes.add(new Filme("Signs","2002","Sci-Fi"));

        return listaFilmes;
    }

}
